# 1. URL de Conexão (Termina em /postgres, sem os parâmetros de user/password)
spring.datasource.url=spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require




# 2. Usuário (O padrão do Supabase é 'postgres' seguido do ID do seu projeto)
spring.datasource.username=spring.datasource.username=postgres.qomshrxdrenpejxvbamy


# 3. Senha (Use a variável de ambiente para não subir ao GitHub)
# No VS Code, você definirá DB_PASSWORD no seu launch.json
spring.datasource.password=${DB_PASSWORD}

# --- Configurações Adicionais Obrigatórias ---

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto para o Hibernate entender que está falando com PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Cria/Atualiza as tabelas automaticamente no Supabase
spring.jpa.hibernate.ddl-auto=update

# Mostra no console as operações que o Java está fazendo no banco
spring.jpa.show-sql=true

# Limita a quantidade de conexões simultâneas (ideal para o plano gratuito)
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# Faz o Java descartar conexões que pararam de responder rápido
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000

api.security.token.secret=95Clwclk8tSCCH/;LU,7&/7bITdSBD8!ixV{<&L/nqmSQp5]aiw:;@UlayM6_SOVhv1+#t5xv5wQ$xezZC?d$I